Labb-1-Avancerat.NET/Controllers/BookController.cs
using Labb_1_Avancerat.NET.Models;
using Labb_1_Avancerat.NET.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Labb_1_Avancerat.NET.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepo;

        public BookController(IBookRepository bookRepo)
        {
            _bookRepo = bookRepo;
        }

        public IActionResult Index()
        {
            var books = _bookRepo.GetAllBooks();

            return View(books);
        }

        [HttpGet("Book/{id}")]
        public IActionResult Book(int id)
        {
            var book = _bookRepo.GetBookById(id);
            return View(book);
        }

    }
}

Labb-1-Avancerat.NET/Controllers/CustomerController.cs
using Labb_1_Avancerat.NET.Models;
using Labb_1_Avancerat.NET.Models.Interfaces;
using Labb_1_Avancerat.NET.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Labb_1_Avancerat.NET.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly IBookRepository _bookRepository;
        private readonly ILoanOrderRepository _loanorderRepo;
        private readonly AppDbContext _context;

        public CustomerController(ICustomerRepository customerRepository, IBookRepository bookRepository, ILoanOrderRepository loanorderRepo, AppDbContext context)
        {
            _customerRepository = customerRepository;
            _bookRepository = bookRepository;
            _loanorderRepo = loanorderRepo;
            _context = context;
        }


        public IActionResult Index()
        {
            var customers = _customerRepository.GetAllCustomers();
            return View(customers);
        }
        [HttpGet("Customer/{id}")]
        public IActionResult Customer(int id, CustomerBooksViewModel customerBooksViewModel)
        {
            customerBooksViewModel = new CustomerBooksViewModel
            {
                Customer = _customerRepository.GetCustomerById(id),
                LoanOrders = _loanorderRepo.GetAllLoanOrders().Where(c => c.CustomerId == id).OrderBy(c => c.DateOfLoan)
            };
            //var customer = _customerRepository.GetCustomerById(id);
            return View(customerBooksViewModel);
        }



        public IActionResult AddOrEditCustomer(int id)
        {
            if (id == 0)
            {
                return View(new Customer());
            }
            else
            {
                return View(_context.Customers.Find(id));
            }
        }
   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEditCustomer([Bind("CustomerId,FirstName,LastName,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                if (customer.CustomerId == 0)
                {
                    
                    _context.Add(customer);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(customer);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customerToDelete = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customerToDelete);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Labb-1-Avancerat.NET/Controllers/LoanController.cs
using Labb_1_Avancerat.NET.Models;
using Labb_1_Avancerat.NET.Models.Interfaces;
using Labb_1_Avancerat.NET.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Labb_1_Avancerat.NET.Controllers
{
    public class LoanController : Controller
    {
        private readonly ICustomerRepository _customerRepo;
        private readonly IBookRepository _bookRepo;
        private readonly ILoanOrderRepository _orderRepo;
        private readonly AppDbContext _context;

        public LoanController(IBookRepository bookRepo, ICustomerRepository customerRepo, ILoanOrderRepository orderRepo, AppDbContext context)
        {
            _bookRepo = bookRepo;
            _customerRepo = customerRepo;
            _orderRepo = orderRepo;
            _context = context;
        }

        public IActionResult Index()
        {
            var loanorders = _orderRepo.GetAllLoanOrders();
            return View(loanorders);
        }

        public IActionResult LoanOrder(int id)
        {
            var loanorder = _orderRepo.GetLoanOrderById(id);
            return View(loanorder);
        }

        public IActionResult AddLoanOrder(int id)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    return View(new LoanOrder());
                }
                else
                {
                    return View(_context.LoanOrders.Find(id));
                }
            }
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddLoanOrder([Bind("LoanOrderId,DateOfLoan,DateOfReturn,CustomerId,BookId")] LoanOrder loanorder)
        {
            if (ModelState.IsValid)
            {
                if (loanorder.LoanOrderId == 0)
                {
                    loanorder.DateOfLoan = DateTime.Now;
                    loanorder.DateOfReturn = DateTime.Now.AddDays(15);
                    _context.LoanOrders.Add(loanorder);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound("Something went Wrong");
                }
            }
            return View(loanorder);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderToDelete = await _context.LoanOrders.FindAsync(id);
            _context.LoanOrders.Remove(orderToDelete);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Labb-1-Avancerat.NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css"
          integrity="sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Tenth navbar example">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Bibliotek</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Loan" asp-action="Index">Loans</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - Labb_1_Avancerat.NET
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>